'use client'

import Link from 'next/link'
import { useParams } from 'next/navigation'
import { Header } from '../../components/Header'
import { Footer } from '../../components/Footer'

const stories = {
  '1': { category: 'HOME GROWING UNITS', date: 'August 26, 2026', title: 'Indoor Grow Tent', dek: 'A compact, efficient solution for families to grow their own food year-round, regardless of weather conditions.', image: 'https://lightpink-jellyfish-915487.hostingersite.com/wp-content/uploads/2026/08/CURRENT.jpeg', paragraphs: ["Our Indoor Grow Tent initiative empowers families to cultivate fresh produce right in their homes.", "These tents are equipped with LED grow lights, ventilation systems, and hydroponic setups, maximizing yield in minimal space. They are perfect for urban environments or areas with harsh climates.", "By reducing reliance on external food sources, families achieve greater food security and access to organic nutrition year-round."] },
  '2': { category: 'HOME GROWING UNITS', date: 'August 20, 2026', title: '"She Shed" Backyard Garden', dek: 'Transforming small backyard spaces into highly productive, easy-to-maintain personal gardens.', image: 'https://lightpink-jellyfish-915487.hostingersite.com/wp-content/uploads/2026/08/VISION.jpg', paragraphs: ["The \"She Shed\" Backyard Garden is designed to make outdoor growing accessible and manageable.", "Using raised beds and strategic companion planting, these gardens yield a surprising amount of fresh vegetables and herbs, even in small spaces.", "It's not just about food; it's about creating a peaceful retreat that connects individuals with nature right in their backyard."] },
  '3': { category: 'RAINWATER HARVESTING', date: 'August 15, 2026', title: 'Home Harvester', dek: 'Simple, effective rainwater catchment systems for residential use, turning rain into a reliable resource.', image: 'https://worldhungerteam.com/wp-content/uploads/2025/12/WhatsApp-Image-2025-12-30-at-1.02.12-AM.jpeg', paragraphs: ["Water is the foundation of any food system. The Home Harvester allows families to capture and store rainwater directly from their roofs.", "This simple intervention provides a crucial backup water supply for domestic gardens during dry spells, ensuring crops survive without relying on municipal water.", "By utilizing this free resource, communities become more resilient to changing weather patterns and droughts."] },
  '4': { category: 'RAINWATER HARVESTING', date: 'August 10, 2026', title: 'Commercial Harvester', dek: 'Large-scale water catchment solutions designed for community gardens and agricultural cooperatives.', image: 'https://worldhungerteam.com/wp-content/uploads/2025/12/klfqBYr7nGziwZTjQJMGzuYOzv4.png', paragraphs: ["For larger agricultural projects, a consistent water supply is critical. Our Commercial Harvester systems are built to meet this demand.", "These high-capacity systems capture thousands of gallons of rainwater, filtering and storing it safely for irrigation during dry seasons.", "This reliable infrastructure allows community gardens to scale their operations and feed more people without draining local groundwater reserves."] },
  '5': { category: 'DOMESTIC FOOD SYSTEMS', date: 'August 5, 2026', title: 'Indoor Community Garden', dek: 'Bringing communities together to grow food collaboratively in repurposed indoor spaces.', image: 'https://worldhungerteam.com/wp-content/uploads/2025/12/WhatsApp-Image-2025-12-30-at-1.03.08-AM.jpeg', paragraphs: ["When outdoor space is limited, we move indoors. The Indoor Community Garden transforms unused buildings into vibrant hubs of agriculture.", "Using vertical farming and hydroponics, these gardens produce food year-round while serving as educational centers for the community.", "It's a shared space where neighbors can learn, grow, and harvest together, strengthening both food security and community bonds."] },
  '6': { category: 'DOMESTIC FOOD SYSTEMS', date: 'August 1, 2026', title: 'Walipini Underground Garden', dek: 'An innovative, climate-resilient approach to year-round farming using subterranean greenhouses.', image: 'https://lightpink-jellyfish-915487.hostingersite.com/wp-content/uploads/2026/08/MISSION.jpg', paragraphs: ["The Walipini, or underground greenhouse, is a remarkable solution for growing food in harsh climates.", "By digging down into the earth and covering the space with transparent material, the Walipini captures solar heat and utilizes the earth's constant temperature.", "This creates a stable, warm environment where crops can thrive even during freezing winters, providing a continuous food supply when it's needed most."] },
} as const



export default function StoryPage() {
  const { slug } = useParams<{ slug: string }>()
  const story = stories[slug as keyof typeof stories] ?? stories['1']
  return <main className="blog-page story-page"><div className="site-header-wrapper"><Header activePath="/blog2" /></div><article><div className="story-article-head"><p className="eyebrow">{story.category} / {story.date}</p><h1>{story.title}</h1><p className="story-dek">{story.dek}</p></div><div className="story-article-image"><img src={story.image} alt="" /></div><div className="story-body">{story.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}<Link className="text-link" href="/blog2">More from the journal <span>↗</span></Link></div></article><Footer /></main>
}
